# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xSgRQVlYeEY_tdPEmVPH7h--0gySi-d8
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import root_mean_squared_error, r2_score

data = pd.read_csv("student_Dataset.csv")

X = data[["Math_Score", "Reading_Score"]]
y = data["Writing_Score"]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20,random_state=42)

print("Training records:", len(X_train))
print("Testing records:", len(X_test))

model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
rmse = root_mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("RMSE:", round(rmse, 2))
print("R-squared:", round(r2, 2))
print("Math Score Coefficient:",round(model.coef_[0], 4))
print("Reading Score Coefficient:",round(model.coef_[1], 4))
print("Intercept:",round(model.intercept_, 4))

results = pd.DataFrame({"Actual Writing Score": y_test.values,"Predicted Writing Score": y_pred.round(2)})
print(results)
print(round(rmse, 2))